### ISSUE TITLE
Warning - Problem with NordVPN 3.18.1

### ISSUE THREAD

**Issue by Kenny606** [theOtherLuke/nordlynx-router#2] opened 2024-05-11 21:33 UTC
A word of warning - Nord has published 3.18.1
I don't know what changed since they don't seem to have even posted released notes for it yet.

However I just happened to be unlucky enough to update to it this morning and it broke the setup.
I spent hours tinkering and even built a new one in VMWare with 3.18.1 but finally gave up.
As soon as I downgraded to 3.18.0 it started working again.

I've had issues connecting to my SonicWall VPN, Teams and a few other services from behind this setup so I was hoping the next release would fix it. Not break the whole setup lol.

(I know what you're thinking but I manage the SonicWALL so I know it's not blocking me because of my VPN and it always worked from behind pfSense with Nord or Express)

I couldn't get the nord client on my machine to connect from behind this setup until the last update so I was hoping the linux update on the router would fix the rest of my issues.

**Comment by theOtherLuke** [comment] 2024-05-12 02:21
Thank you for sharing this. I will check this on my setup and report back.

As for connecting a seperate vpn for remote access, I made an additional connection between my modem and firewall, bypassing the nord container, and only permit incoming connections for my remote access vpn on that port while all other traffic still goes through nord.

**Comment by theOtherLuke** [comment] 2024-08-03 22:52
Unable to reproduce this issue. However, that does not mean someone else won't encounter it. I believe it is most likely a configuration issue when using VMWare as a hypervisor. I am currently running Proxmox. Though I haven't tried any other hypervisors. I my try on one of my servers running TrueNAS Scale natively. 

No further input so closing. Thank you for the submission.

**Closed** 2024-08-03 22:52 UTC
